version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 32123:5432
    environment:
      - POSTGRES_PASSWORD=main
      - POSTGRES_USER=main
      - POSTGRES_DB=TareaLSpring